(()=>{"use strict";
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const toast=m=>{const t=$("#toast");if(!t)return;t.textContent=m;t.style.display="block";clearTimeout(window.ccjToastTimer);window.ccjToastTimer=setTimeout(()=>t.style.display="none",2600)};
const dt=v=>v?new Date(v+"T00:00:00"):null,fmt=d=>d.toLocaleDateString("en-IN",{day:"2-digit",month:"short",year:"numeric"}),money=n=>Number(n).toLocaleString("en-IN",{minimumFractionDigits:2,maximumFractionDigits:2});
const download=(name,text,type="text/plain;charset=utf-8")=>{const blob=new Blob([text],{type}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=name||"download.txt";a.click();setTimeout(()=>URL.revokeObjectURL(url),1200)};
const copy=async(text,textarea)=>{try{await navigator.clipboard.writeText(text)}catch{if(textarea){textarea.focus();textarea.select();document.execCommand("copy")}else throw new Error("Copy unavailable")}};
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
if($("#year"))$("#year").textContent=new Date().getFullYear();
const menu=$("#menuBtn"),nav=$("#navLinks");if(menu&&nav){menu.onclick=()=>nav.classList.toggle("open");nav.querySelectorAll("a").forEach(a=>a.onclick=()=>nav.classList.remove("open"))}
if($("#toolSearch")){const run=()=>{const q=$("#toolSearch").value.toLowerCase();let n=0;$$('#allTools .tool').forEach(c=>{const ok=c.innerText.toLowerCase().includes(q);c.classList.toggle("hidden",!ok);if(ok)n++});$("#noToolMatch").classList.toggle("hidden",n>0)};$("#toolSearch").oninput=run;$("#clearToolSearch").onclick=()=>{$("#toolSearch").value="";run()}}
if($("#dateCalc"))$("#dateCalc").onclick=()=>{const a=dt($("#dateStart").value),b=dt($("#dateEnd").value);if(!a||!b)return toast("Select both dates.");const n=Math.round((b-a)/86400000);$("#dateResult").textContent=`Difference: ${Math.abs(n)} days. Inclusive count: ${Math.abs(n)+1} days. ${n<0?"The end date is before the start date.":""}`};
if($("#interestCalc"))$("#interestCalc").onclick=()=>{const raw=["principal","rate","years"].map(id=>$("#"+id).value);if(raw.some(v=>v===""||!Number.isFinite(+v)||+v<0))return toast("Enter valid non-negative values.");const [p,r,t]=raw.map(Number),si=p*r*t/100;$("#interestResult").textContent=`Simple interest: ₹${money(si)}\nTotal amount: ₹${money(p+si)}`};
if($("#ageCalc"))$("#ageCalc").onclick=()=>{let d=dt($("#dob").value),a=dt($("#asOf").value);if(!d||!a)return toast("Choose both dates.");if(d>a)return toast("DOB cannot be after as-of date.");let y=a.getFullYear()-d.getFullYear(),m=a.getMonth()-d.getMonth(),day=a.getDate()-d.getDate();if(day<0){m--;day+=new Date(a.getFullYear(),a.getMonth(),0).getDate()}if(m<0){y--;m+=12}$("#ageResult").textContent=`Age: ${y} years, ${m} months, ${day} days.`};
if($("#gstCalc"))$("#gstCalc").onclick=()=>{const raw=$("#gstAmount").value,a=+raw,r=+$("#gstRate").value;if(raw===""||!Number.isFinite(a)||a<0)return toast("Enter a valid amount.");if($("#gstMode").value==="add"){const g=a*r/100;$("#gstResult").textContent=`GST: ₹${money(g)}\nTotal: ₹${money(a+g)}`}else{const base=a/(1+r/100);$("#gstResult").textContent=`Base amount: ₹${money(base)}\nIncluded GST: ₹${money(a-base)}`}};
if($("#limitCalc"))$("#limitCalc").onclick=()=>{let d=dt($("#limitStart").value);if(!d)return toast("Choose a reference date.");const y=Number($("#limitYears").value||0),m=Number($("#limitMonths").value||0),days=Number($("#limitDays").value||0);if(![y,m,days].every(Number.isInteger))return toast("Enter whole numbers.");const targetDay=d.getDate();d.setDate(1);d.setFullYear(d.getFullYear()+y);d.setMonth(d.getMonth()+m);const last=new Date(d.getFullYear(),d.getMonth()+1,0).getDate();d.setDate(Math.min(targetDay,last));d.setDate(d.getDate()+days);$("#limitResult").textContent=`Calendar arithmetic result: ${fmt(d)}.\nThis is not a legal limitation opinion.`};
const drafts={
notice:`LEGAL NOTICE — STARTER TEMPLATE\n\nDate: [DD/MM/YYYY]\nFrom: [Client name and address]\nThrough Counsel: [Advocate name and address]\nTo: [Recipient name and address]\nSubject: Legal notice regarding [subject]\n\nSir/Madam,\nUnder instructions from my client [name], I state:\n1. [Relevant facts chronologically]\n2. [Act/omission and relevant dates]\n3. [Prior communication, if any]\n\nYou are called upon to [specific lawful demand] within [period] of receipt, failing which my client may pursue remedies available under applicable law.\n\n[Advocate name / enrollment / contact]\n\nNOTE: Adapt to facts, statute, jurisdiction, limitation and service requirements. Review before issue.`,
application:`IN THE COURT OF [COURT NAME] AT [PLACE]\n[Case title / number]\n\nAPPLICATION ON BEHALF OF [APPLICANT]\n\nMost respectfully submitted:\n1. [Brief facts]\n2. [Grounds supporting request]\n3. [Specific relief sought]\n\nPRAYER\nIt is respectfully prayed that this Hon'ble Court may be pleased to [precise relief], in the interest of justice.\n\nPlace: [Place]   Date: [Date]\nApplicant / Counsel: [Name and signature]\n\nNOTE: Check applicable procedural law, court rules, format and annexures.`,
affidavit:`AFFIDAVIT — STARTER FORMAT\n\nI, [full name], aged [age], [occupation], resident of [address], solemnly affirm:\n1. [Fact within personal knowledge]\n2. [Additional fact]\n\nVERIFICATION\nI verify that paragraphs [x] are true to my knowledge and paragraphs [y] are based on information believed to be true. Nothing material has been concealed.\n\nPlace: [Place]  Date: [Date]\nDEPONENT: [Signature]\nAttestation: [As required by applicable rules]\n\nNOTE: Use the verification and attestation required for this forum and purpose.`,
adjournment:`IN THE COURT OF [COURT] AT [PLACE]\n[Case title / number]\n\nAPPLICATION SEEKING ADJOURNMENT\n1. Matter is listed today for [purpose/stage].\n2. Due to [specific bona fide reason], applicant is unable to proceed today.\n3. Request is made in good faith and not to delay proceedings.\n\nPRAYER\nKindly grant a short adjournment and fix a convenient next date.\n\nPlace / Date: [Details]\n[Applicant / Advocate]\n\nNOTE: State accurate facts. Grant is at the court's discretion.`,
bail:`BAIL APPLICATION — OUTLINE\nCourt: [Competent court]\nApplicant: [Name]\nCase / FIR No.: [Number] | Police Station: [Name]\nOffences alleged: [As recorded]\nType: [Regular / Anticipatory]\n\n1. Brief facts and procedural status\n2. Applicant's role and allegations\n3. Fact-specific grounds supported by record\n4. Cooperation, antecedents and relevant facts\n5. Conditions applicant can comply with\n\nPRAYER: Grant [type] bail on appropriate terms.\nPlace / Date / Counsel\n\nNOTE: Confirm current law, jurisdiction, case record and procedure.`,
demand:`PAYMENT DEMAND NOTICE — STARTER\nDate: [Date]\nTo: [Name and address]\nFrom: [Client and address]\nSubject: Demand for payment of [amount / invoice]\n\n1. [Transaction / agreement / invoice details]\n2. ₹[amount] became due on [date].\n3. Despite [reminders], the amount remains unpaid.\n\nYou are requested to pay ₹[amount] or respond in writing within [period]. If unresolved, my client may consider remedies available under applicable law.\n\n[Advocate details]\n\nNOTE: Verify evidence, contract, limitation, jurisdiction and statutory notice requirements.`,
undertaking:`UNDERTAKING — STARTER\n\nI, [full name], resident of [address], undertake as follows:\n1. [Specific undertaking]\n2. I shall [action / deadline / condition].\n3. I understand that non-compliance may have consequences under applicable law or relevant order/agreement.\n\nPurpose: [Purpose]\nPlace / Date: [Details]\nSignature: __________  Name: [Name]\nWitness / attestation: [If required]\n\nNOTE: Check the receiving authority's prescribed format and legal requirements.`,
vakalatnama:`VAKALATNAMA — CHECKLIST\n☐ Correct court / forum and case number\n☐ Parties' names and status checked\n☐ Advocate name(s) and enrollment details\n☐ Client signature / thumb impression as required\n☐ Advocate acceptance and signature\n☐ Required stamp / fee, if applicable\n☐ Authority / ID documents, if required\n☐ Date and place completed\n☐ Current court rules and local practice checked\n\nChecklist only; use the prescribed format applicable to the court.`
};
const draftSelect=$("#draftSelect"),draftText=$("#draftText");if(draftSelect&&draftText){const load=()=>draftText.value=drafts[draftSelect.value]||"";draftSelect.onchange=load;load();$("#copyDraft").onclick=async()=>{try{await copy(draftText.value,draftText);toast("Draft copied")}catch{toast("Copy not available")}};$("#downloadDraft").onclick=()=>download(draftSelect.value+"-starter.txt",draftText.value);$("#resetDraft").onclick=load}
let checks=[];function renderChecks(){const box=$("#checkList");if(!box)return;box.innerHTML=checks.map((c,i)=>`<div class="list-item ${c.done?"done":""}"><input type="checkbox" data-check="${i}" ${c.done?"checked":""}><span class="grow">${esc(c.text)}</span><button data-rmcheck="${i}">Remove</button></div>`).join("")||'<p class="muted">No checklist items yet.</p>';$$("[data-check]").forEach(x=>x.onchange=()=>{checks[+x.dataset.check].done=x.checked;renderChecks()});$$("[data-rmcheck]").forEach(x=>x.onclick=()=>{checks.splice(+x.dataset.rmcheck,1);renderChecks()})}
if($("#checkForm")){$("#checkForm").onsubmit=e=>{e.preventDefault();checks.push({text:$("#checkInput").value.trim(),done:false});$("#checkInput").value="";renderChecks()};$("#clearChecklist").onclick=()=>{checks=[];renderChecks()};$("#exportChecklist").onclick=()=>download("document-checklist.txt",checks.map(c=>(c.done?"[x] ":"[ ] ")+c.text).join("\n"));renderChecks()}
const CASEKEY="ccj_cases_v1",FEEKEY="ccj_fees_v1";const read=(k)=>{try{const x=JSON.parse(localStorage.getItem(k)||"[]");return Array.isArray(x)?x:[]}catch{return []}},write=(k,x)=>{try{localStorage.setItem(k,JSON.stringify(x));return true}catch{return false}};
let cases=read(CASEKEY);function renderCases(){const box=$("#caseList");if(!box)return;box.innerHTML=cases.map((c,i)=>`<div class="list-item"><div class="grow"><b>${esc(c.name)}</b><div class="muted">${c.date?"Next date: "+esc(c.date):"No next date"}${c.stage?" · "+esc(c.stage):""}<br>${esc(c.notes||"")}</div></div><button data-delcase="${i}">Delete</button></div>`).join("")||'<p class="muted">No cases saved yet.</p>';$$("[data-delcase]").forEach(b=>b.onclick=()=>{cases.splice(+b.dataset.delcase,1);write(CASEKEY,cases);renderCases()})}
if($("#caseForm")){$("#caseForm").onsubmit=e=>{e.preventDefault();cases.unshift({name:$("#caseName").value.trim(),date:$("#caseDate").value,stage:$("#caseStage").value.trim(),notes:$("#caseNotes").value.trim()});write(CASEKEY,cases);renderCases();e.target.reset();toast("Case saved in this browser")};$("#exportCases").onclick=()=>download("courtcasejankari-cases.json",JSON.stringify(cases,null,2),"application/json");$("#clearCases").onclick=()=>{if(confirm("Delete all locally saved cases?")){cases=[];write(CASEKEY,cases);renderCases()}};$("#importCasesBtn").onclick=()=>$("#importCasesFile").click();$("#importCasesFile").onchange=async e=>{try{const arr=JSON.parse(await e.target.files[0].text());if(!Array.isArray(arr))throw 0;cases=arr;write(CASEKEY,cases);renderCases();toast("Imported")}catch{toast("Invalid JSON backup")}e.target.value=""};renderCases()}
let fees=read(FEEKEY);function renderFees(){const box=$("#feeList");if(!box)return;const net=fees.reduce((s,f)=>s+(f.type==="income"?f.amount:-f.amount),0);$("#feeTotal").textContent="Net total: ₹"+money(net);box.innerHTML=fees.map((f,i)=>`<div class="list-item"><div class="grow"><b>${esc(f.desc)} · ${f.type==="income"?"Fee received":"Expense"}</b><div class="muted">₹${money(f.amount)} · ${esc(f.date)}</div></div><button data-delfee="${i}">Delete</button></div>`).join("")||'<p class="muted">No entries saved yet.</p>';$$("[data-delfee]").forEach(b=>b.onclick=()=>{fees.splice(+b.dataset.delfee,1);write(FEEKEY,fees);renderFees()})}
if($("#feeForm")){$("#feeForm").onsubmit=e=>{e.preventDefault();const amount=+$("#feeAmount").value;if(!Number.isFinite(amount)||amount<0)return toast("Enter valid amount.");fees.unshift({desc:$("#feeDesc").value.trim(),type:$("#feeType").value,amount,date:new Date().toLocaleDateString("en-IN")});write(FEEKEY,fees);renderFees();e.target.reset();toast("Entry saved locally")};$("#exportFees").onclick=()=>download("courtcasejankari-fees.json",JSON.stringify(fees,null,2),"application/json");$("#clearFees").onclick=()=>{if(confirm("Delete all fee entries?")){fees=[];write(FEEKEY,fees);renderFees()}};renderFees()}
if($("#copyText"))$("#copyText").onclick=async()=>{try{await copy($("#textPad").value,$("#textPad"));$("#textStatus").textContent="Copied.";toast("Text copied")}catch{toast("Copy unavailable")}};
if($("#downloadText"))$("#downloadText").onclick=()=>download("courtcasejankari-note.txt",$("#textPad").value);
if($("#clearText"))$("#clearText").onclick=()=>{$("#textPad").value="";$("#textStatus").textContent="Cleared."};
if($("#downloadDoc"))$("#downloadDoc").onclick=()=>{let n=$("#docName").value.trim()||"legal-document.txt";if(!/\.[a-z0-9]{1,8}$/i.test(n))n+=".txt";download(n,$("#docText").value)};
})();